apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
spec:
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
      - name: simulator
        image: acr22.azurecr.io/simulator:v4
        ports:
        - containerPort: 8000
